on: push
name: Build and Publish
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test
      run: make test
    - name: Lint
      run: make lint
    - name: Build
      run: make build
    - name: Publish Filter
      uses: actions/bin/filter@master
      with:
        args: branch master
    - name: Docker Login
      run: docker login
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: Publish
      run: make publish
