on: push
name: Build and Publish
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test
      run: make test
#    - name: Lint
#      run: make lint
    - name: Docker Login
      if: github.ref == 'refs/heads/master' 
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - run: |
        make build
        make publish
